#!/bin/bash
exit 1 #comment this line when it's all right
aiAE=0
#
# --- Paste the varables from aiva1 here ---

# ---
#
aiERRORS="ERRORS:\n"
dhcpcd
#comment the next line if you want to use homed
systemctl mask systemd-homed.service systemd-userdbd.socket systemd-userdbd.service
sleep 5s
echo 'Testing connection...'
sleep 1s
curl -Is http://www.google.com
if [ $? -gt 0 ]; then
read -p "No internet connection detected! Continue ? (y/n): " ireply
if [ "$ireply" != "y" ]; then
exit
fi
else
echo 'Internet is OK'
fi
pacman -Syyu --noconfirm
# - Users
groupadd sudo
groupadd -r autologin
useradd -m $aiUSER
echo "Insert the new password for ${aiUSER}:"
if [ $aiUSERP ]; then
printf "$aiUSERP\n$aiUSERP" | passwd $aiUSER
else
passwd -d $aiUSER
fi
usermod -aG sudo $aiUSER
printf "\nDefaults targetpw\n%%sudo ALL=(ALL) ALL\n" >> /etc/sudoers
#
# --- Network ---
pacman -S networkmanager network-manager-applet samba net-tools gufw --noconfirm

systemctl enable NetworkManager
# - Local Network Share
cat << 'EOT' > /etc/samba/smb.conf
[global]
workgroup = WORKGROUP
server string = 
log file = /var/log/samba/smb.log
log level = 0
max log size = 300
map to guest = Bad User
[printers]
comment = 
path = /usr/spool/samba
guest ok = yes
printable = yes
browseable = yes
writable = no

EOT
if [ $aiSHARES -eq 1 ]; then
systemctl enable smb nmb
fi
echo "Insert the new samba administration password:"
printf "$aiROOTP\n$aiROOTP" | smbpasswd -a nobody
# --- UI ---
# - Video Drivers
case "$aiVDRIVERS" in
1)
pacman -S xf86-video-intel vulkan-intel --noconfirm
;;
2)
pacman -S xf86-video-amdgpu vulkan-radeon --noconfirm
;;
3)
pacman -S xf86-video-ati vulkan-radeon --noconfirm
;;
4)
pacman -S nvidia-dkms nvidia-settings --noconfirm
;;
5)	
pacman -S xf86-video-nouveau --noconfirm
;;
esac
# Desktop
if [ $aiDE -gt 0 ]; then
pacman -S xorg --noconfirm
case "$aiDE" in
1)
pacman -S xfce4 xfce4-goodies --noconfirm
pacman -R xfce4-clipman-plugin --noconfirm
;;
2)
pacman -S lxde obconf slock xfce4-power-manager dunst --noconfirm
pacman -R lxdm --noconfirm
;;
esac
pacman -S gvfs-smb ntfs-3g gnome-icon-theme --noconfirm
pacman -S lightdm lightdm-gtk-greeter --noconfirm
systemctl enable lightdm
sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/' /etc/lightdm/lightdm.conf
#loadkeys $aiKEYLANG
if [ $aiKEYLANG != "en" ]; then
localectl set-x11-keymap $aiKEYLANG
fi
# Autologin
if [ $aiAUTOLOGIN -eq 1 ]; then
gpasswd -a $aiUSER autologin
sed -i 's/#autologin-user=/autologin-user=${aiUSER}/' /etc/lightdm/lightdm.conf
fi
fi
# Audio
pacman -S alsa-utils pulseaudio-alsa paprefs pavucontrol --noconfirm
# Printer
if [ $aiPRINT -eq 1 ]; then
pacman -S cups cups-pdf system-config-printer --noconfirm
systemctl enable org.cups.cupsd
fi
# Bluetooth
if [ $aiBT -eq 1 ]; then
pacman -S bluez bluez-utils --noconfirm
systemctl enable bluetooth
fi
#
# --- Software ---
pacman -S gnu-free-fonts font-bh-ttf ttf-liberation ttf-dejavu ttf-ubuntu-font-family ttf-linux-libertine ttf-opensans ttf-hannom ttf-hanazono ttf-baekmuk --noconfirm
pacman -S gtk2-perl gtk-engine-murrine lightdm-gtk-greeter-settings gnome-packagekit git sshfs openssh wget grub-customizer rxvt-unicode xf86-input-libinput p7zip htop --noconfirm
if [ $aiDE -gt 0 ]; then
pacman -S xarchiver hardinfo onboard catfish alacarte gnome-calculator gparted libreoffice-still vlc gimp firefox evince notepadqq geany claws-mail hexchat utox xboard gnuchess aisleriot --noconfirm
pacman -S archlinux-wallpaper adapta-gtk-theme arc-gtk-theme arc-icon-theme arc-solid-gtk-theme papirus-icon-theme breeze-gtk breeze-icons materia-gtk-theme deepin-gtk-theme deepin-icon-theme elementary-icon-theme lxde-icon-theme --noconfirm
if [ $aiDE -gt 0 ]; then
cat << 'EOT' > /etc/skel/.Xresources
*.foreground: #fafdfb
*.background: #2e3235
*.cursorColor: #fafdfb
*.color0: #282a2e
*.color8: #373b41
*.color1: #a54242
*.color9: #cc6666
*.color2: #8c9440
*.color10: #b5bd68
*.color3: #de935f
*.color11: #f0c674
*.color4: #5f819d
*.color12: #81a2be
*.color5: #85678f
*.color13: #b294bb
*.color6: #5e8d87
*.color14: #8abeb7
*.color7: #707880
*.color15: #fafdfb
URxvt*font: xft:inconsolata:size=13:antialias=true
EOT
mkdir -p /etc/skel/.config/dunst
cat << 'EOT' > /etc/skel/.config/dunst/dunstrc
[global]
    monitor = 0
    follow = mouse
    geometry = "0x5-30+30"
    progress_bar = true
    progress_bar_height = 15
    progress_bar_frame_width = 1
    progress_bar_min_width = 150
    progress_bar_max_width = 500
    indicate_hidden = yes
    shrink = yes
    transparency = 0
    notification_height = 0
    separator_height = 2
    padding = 7
    horizontal_padding = 8
    text_icon_padding = 10
    frame_width = 0
    frame_color = "#000000"
    separator_color = frame
    sort = no
    idle_threshold = 0
    font = Sans 14
    line_height = 0
    markup = full
    format = "<b>%a-%s</b>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = -1
    word_wrap = yes
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = false
    hide_duplicate_count = false
    show_indicators = no
    icon_position = left
    min_icon_size = 20
    max_icon_size = 512
    icon_path = /usr/share/icons/gnome/48x48/status/:/usr/share/icons/gnome/48x48/devices/
    sticky_history = yes
    history_length = 5
    dmenu = /usr/bin/dmenu -p dunst:
    browser = /usr/bin/firefox -new-tab
    always_run_script = true
    title = Dunst
    class = Dunst
    startup_notification = false
    verbosity = crit
    corner_radius = 5
    ignore_dbusclose = false
    force_xwayland = false
    force_xinerama = false
    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all
[experimental]
    per_monitor_dpi = false
[shortcuts]
[urgency_low]
    background = "#333333"
    foreground = "#dddddd"
    timeout = 3
[urgency_normal]
    background = "#555555"
    foreground = "#dddddd"
    timeout = 5
[urgency_critical]
    background = "#555555"
    foreground = "#e05915"
    timeout = 0
EOT
if [ $aiLOL ]; then
pacman -S libreoffice-still-$aiLOL --noconfirm
fi
pacman -Rd chromaprint --noconfirm
# - Autoupdate
case "$aiUPDATE" in
1)
printf "[Unit]\nDescription=Simple Arch auto update service\n\n[Service]\nType=idle\nRemainAfterExit=no\nExecStart=+urxvt -e bash -c 'printf \"\\\n SIMPLE ARCH AUTO UPDATE\\\n\\\n\";sudo pacman -Syu --noconfirm && paccache -rk1;bash'\n\n[Install]\nWantedBy=default.target" > /etc/systemd/user/updArch.service
printf "[Unit]\nDescription=Simple Arch auto update timer\n\n[Timer]\nOnCalendar=Mon *-*-* 11:00:00\nPersistent=true\n\n[Install]\nWantedBy=timers.target" > /etc/systemd/user/updArch.timer
systemctl --global enable updArch.timer
;;
2)
printf "[Unit]\nDescription=Simple Arch quiet auto update service\n\n[Service]\nType=idle\nRemainAfterExit=no\nExecStart=pacman -Syu --noconfirm\nExecStartPost=paccache -rk1\nStandardOutput=file:/var/log/saul.log\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/updArchS.service
printf "[Unit]\nDescription=Simple Arch quiet auto update timer\n\n[Timer]\nOnCalendar=Mon *-*-* 11:00:00\nPersistent=true\n\n[Install]\nWantedBy=timers.target" > /etc/systemd/system/updArchS.timer
systemctl enable updArchS.timer
;;
esac
# - Restart
printf "\n\n --- INSTALLATION COMPLETE ---\nRemember to review and delete installation files in /root (the file ivars contains the passwords) !\n"
if [ $aiAE -eq 1 ]; then
echo -e $aiERRORS
fi
read -p "Reboot ? (y/n): " ireply
if [ "$ireply" = "y" ]; then
reboot
fi
exit 0