#!/bin/bash
exit 1 #comment this line when it's all right
# --- Paste vars here ---
# ---
#
# - Timezone
if [ $aiGOT -eq 1 ]; then
ln -sf /usr/share/zoneinfo/Region/City /etc/localtime
else
ln -sf /usr/share/zoneinfo/Etc/GMT+X /etc/localtime
fi
hwclock --systohc
echo $aiLOCALE >> /etc/locale.gen
locale-gen
echo $aiLOCALEL > /etc/locale.conf
# - Keyboard
if [ $aiKEYLANG != "en" ]; then
echo "KEYMAP=$aiKEYLANG" > /etc/vconsole.conf
loadkeys $aiKEYLANG
fi
# - Nework conf
echo $aiPCNAME > /etc/hostname
printf "127.0.0.1 localhost\n::1 localhost\n127.0.1.1 ${aiPCNAME}.localdomain	${aiPCNAME}\n" > /etc/hosts
# - Root password
echo "Insert the new password for root:"
printf "$aiROOTP\n$aiROOTP" | passwd
# - Boot
if [ $aiUEFI -eq 1 ]; then
mkdir /boot/efi
mount /dev/$aiBOOTP /boot/efi
mkdir /boot/efi/EFI
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
else
grub-install --target=i386-pc /dev/$aiDISK
fi
grub-mkconfig -o /boot/grub/grub.cfg
exit
