#!/bin/bash
exit 1 #comment this line when it's all right
# - Timezone
ln -sf /usr/share/zoneinfo/Region/City /etc/localtime
# - OR
#ln -sf /usr/share/zoneinfo/Etc/GMT+X /etc/localtime # X is the offset but it will not change the daylight saving time
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
# - Keyboard
echo "KEYMAP=en" > /etc/vconsole.conf
loadkeys "en"
# - Nework conf
echo "MYdevicename" > /etc/hostname
printf "127.0.0.1 localhost\n::1 localhost\n127.0.1.1 myhostname.localdomain	myhostname\n" > /etc/hosts
# - Root password
echo "Insert the new password for root:"
passwd
# - Boot efi
mkdir /boot/efi
mount /dev/sdXY /boot/efi
mkdir /boot/efi/EFI
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
# - OR
#grub-install --target=i386-pc /dev/sdX #legacy (boot mbr)
grub-mkconfig -o /boot/grub/grub.cfg #uefi and legacy
exit
