#!/bin/bash
exit 1 #comment this line when it's all right
dhcpcd
#comment the next line if you want to use homed
systemctl mask systemd-homed.service systemd-userdbd.socket systemd-userdbd.service
sleep 6s
pacman -Syy
# - Users
groupadd sudo
groupadd -r autologin
useradd -m MYuser
echo "Insert the new password for the user:"
passwd MYuser
usermod -aG sudo MYuser
printf "\nDefaults targetpw\n%%sudo ALL=(ALL) ALL\n" >> /etc/sudoers
#
# --- Network ---
pacman -S networkmanager network-manager-applet samba net-tools gufw --noconfirm
systemctl enable NetworkManager
# - Local Network Share
cat << EOT > /etc/samba/smb.conf
[global]
workgroup = WORKGROUP
server string = 
log file = /var/log/samba/smb.log
log level = 0
max log size = 300
map to guest = Bad User
[printers]
comment = 
path = /usr/spool/samba
guest ok = yes
printable = yes
browseable = yes
writable = no

EOT
systemctl enable --now smb nmb
echo "Insert the samba administration new password:"
smbpasswd -a nobody
# --- UI ---
# - Video Drivers
#pacman -S xf86-video-intel vulkan-intel --noconfirm
# OR
#pacman -S xf86-video-amdgpu vulkan-radeon --noconfirm
# OR
#pacman -S xf86-video-ati vulkan-radeon --noconfirm
# OR
#pacman -S nvidia-dkms nvidia-settings --noconfirm
# OR
#pacman -S xf86-video-nouveau --noconfirm
pacman -S xorg --noconfirm
pacman -S xfce4 xfce4-goodies --noconfirm
pacman -R xfce4-clipman-plugin --noconfirm
# OR
#pacman -S lxde obconf slim xfce4-power-manager --noconfirm
#pacman -R lxdm --noconfirm
pacman -S gvfs-smb ntfs-3g gnome-icon-theme --noconfirm
pacman -S lightdm lightdm-gtk-greeter --noconfirm
systemctl enable lightdm
sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/' /etc/lightdm/lightdm.conf
#loadkeys "en"
localectl set-x11-keymap "en"
# - Autologin
gpasswd -a MYuser autologin
sed -i 's/#autologin-user=/autologin-user=MYuser/' /etc/lightdm/lightdm.conf
# - Audio
pacman -S alsa-utils pulseaudio-alsa paprefs pavucontrol --noconfirm
# - Printer
pacman -S cups cups-pdf system-config-printer --noconfirm
systemctl enable org.cups.cupsd
# - Bluetooth
pacman -S bluez bluez-utils --noconfirm
systemctl enable bluetooth
#
# --- Software ---
# - fonts
pacman -S gnu-free-fonts font-bh-ttf ttf-liberation ttf-dejavu ttf-ubuntu-font-family ttf-linux-libertine ttf-opensans ttf-hannom ttf-hanazono ttf-baekmuk --noconfirm
pacman -S gtk2-perl gnome-packagekit git sshfs openssh wget grub-customizer rxvt-unicode xf86-input-libinput p7zip xarchiver --noconfirm
pacman -S htop hardinfo onboard catfish alacarte gnome-calculator gparted libreoffice-still vlc gimp firefox evince notepadqq geany claws-mail hexchat utox xboard gnuchess aisleriot --noconfirm
#pacman -S libreoffice-still-MYlang --noconfirm #language pack
# - themes
pacman -S archlinux-wallpaper adapta-gtk-theme arc-gtk-theme arc-icon-theme arc-solid-gtk-theme moka-icon-theme papirus-icon-theme breeze-gtk breeze-icons materia-gtk-theme deepin-gtk-theme deepin-icon-theme elementary-icon-theme lxde-icon-theme --noconfirm
pacman -R gst-plugins-bad --noconfirm
# - Auto Update
printf "[Unit]\nDescription=Simple Arch auto update service\n\n[Service]\nType=idle\nRemainAfterExit=no\nExecStart=+urxvt -e bash -c 'printf \"\\\n SIMPLE ARCH AUTO UPDATE\\\n\\\n\";sudo pacman -Syu --noconfirm && paccache -rk1;bash'\n\n[Install]\nWantedBy=default.target" > /etc/systemd/user/updArch.service
printf "[Unit]\nDescription=Simple Arch auto update timer\n\n[Timer]\nOnCalendar=Mon *-*-* 11:00:00\nPersistent=true\n\n[Install]\nWantedBy=timers.target" > /etc/systemd/user/updArch.timer
systemctl --global enable updArch.timer
# - Invisible Auto Update
#printf "[Unit]\nDescription=Simple Arch quiet auto update service\n\n[Service]\nType=idle\nRemainAfterExit=no\nExecStart=pacman -Syu --noconfirm\nExecStartPost=paccache -rk1\nStandardOutput=file:/var/log/saul.log\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/updArchS.service
#printf "[Unit]\nDescription=Simple Arch quiet auto update timer\n\n[Timer]\nOnCalendar=Mon *-*-* 11:00:00\nPersistent=true\n\n[Install]\nWantedBy=timers.target" > /etc/systemd/system/updArchS.timer
#systemctl enable updArchS.timer
# - Restart
printf "\nRemember to review and delete install files in /root !\nThe file ivars contains passwords !\n"
read -p "Installation complete !"
