#!/bin/bash
# Create the partitions before.
# you should mount the scripts disk under /ai (for the arch-chroot)
printf "\n\n ARCH-IN edit - part1\nRead the guide and carefully edit the script files.\nBackup your data before!\n"
exit 1 #comment this line when it's all right
#
# --- Initial Settings ---
loadkeys en
dhcpcd
timedatectl set-ntp true
#cfdisk
# - Boot partition flag
parted /dev/sdX set 1 esp on
# - OR
#parted /dev/sdX set 1 bios_grub on
# - Format
mkfs.ext4 /dev/sdXY
mkswap /dev/sdXY
mkfs.fat -F 32 /dev/sdXY
# - Mount
swapon /dev/sdXY
mount /dev/sdXY /mnt
# --- Files Copy ---
pacstrap /mnt base linux-lts linux-lts-headers linux-firmware base-devel grub efibootmgr os-prober pacman-contrib dhcpcd nano vi
#pacstrap /mnt base linux linux-headers linux-firmware base-devel grub efibootmgr os-prober pacman-contrib dhcpcd nano vi
genfstab -U /mnt >> /mnt/etc/fstab
# --- Chroot ---
cp /ai/aiedchr /mnt/root #edit the location of the scripts
cp /ai/aied2 /mnt/root #edit the location of the scripts
arch-chroot /mnt ./root/aiedchr
read -p "First part complete. Press any key to reboot. "
reboot
