#!/bin/bash
clear
aiAE=0
aiERRORS="ERRORS:\n"
echo "ARCHIN INSTALLER - second part"
read -p "Press ctrl+c to quit or enter to continue..."
source /root/ivars
if [ $aiFC -ne 1 ]; then
echo "Install vars file not found or vars error !";
exit 1
fi
dhcpcd
#comment the next line if you want to use homed
systemctl mask systemd-homed.service systemd-userdbd.socket systemd-userdbd.service
sleep 5s
echo 'Testing connection...'
sleep 1s
curl -Is http://www.google.com
if [ $? -gt 0 ]; then
read -p "No internet connection detected! Continue ? (y/n): " ireply
if [ "$ireply" != "y" ]; then
exit
fi
else
echo 'Internet is OK'
fi
systemctl mask systemd-homed.service systemd-userdbd.socket systemd-userdbd.service
pacman -Syy
# - Users
groupadd sudo
groupadd -r autologin
useradd -m $aiUSER
if [ $aiUSERP ]; then
printf "$aiUSERP\n$aiUSERP" | passwd $aiUSER
else
passwd -d $aiUSER
fi
usermod -aG sudo $aiUSER
printf "\nDefaults targetpw\n%%sudo ALL=(ALL) ALL\n" >> /etc/sudoers
# --- Network ---
pacman -S networkmanager network-manager-applet samba net-tools gufw --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Network manager installation error"; fi
systemctl enable NetworkManager
# - Local Network Share
cat << 'EOT' > /etc/samba/smb.conf
[global]
workgroup = WORKGROUP
server string = 
log file = /var/log/samba/smb.log
log level = 0
max log size = 300
map to guest = Bad User
[printers]
comment = 
path = /usr/spool/samba
guest ok = yes
printable = yes
browseable = yes
writable = no

EOT
if [ $aiSHARES = "y" ]; then
systemctl enable smb nmb
fi
printf "$aiROOTP\n$aiROOTP" | smbpasswd -a nobody
# --- UI ---
# - Video Drivers
aiTE=0
case "$aiVDRIVERS" in
1)
pacman -S xf86-video-intel vulkan-intel --noconfirm
aiTE=$?
;;
2)
pacman -S xf86-video-amdgpu vulkan-radeon --noconfirm
aiTE=$?
;;
3)
pacman -S xf86-video-ati vulkan-radeon --noconfirm
aiTE=$?
;;
4)
pacman -S nvidia-dkms nvidia-settings --noconfirm
aiTE=$?
;;
5)	
pacman -S mesa xf86-video-nouveau --noconfirm
aiTE=$?
;;
esac
if [ $aiTE -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Video drivers installation error\n"; fi
if [ $aiDE -gt 0 ]; then
pacman -S xorg --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - X installation error\n"; fi
aiTE=0
case "$aiDE" in
1)
pacman -S xfce4 xfce4-goodies --noconfirm
aiTE=$?
pacman -R xfce4-clipman-plugin --noconfirm
;;
2)
pacman -S lxde obconf slock xfce4-power-manager --noconfirm
aiTE=$?
pacman -R lxdm --noconfirm
;;
esac
if [ $aiTE -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Desktop environment installation error\n"; fi
pacman -S gvfs-smb ntfs-3g gnome-icon-theme --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Window manager extras installation error\n"; fi
pacman -S lightdm lightdm-gtk-greeter --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Login manager installation error\n"; fi
systemctl enable lightdm
sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/' /etc/lightdm/lightdm.conf
if [ $aiKEYLANG != "en" ]; then
localectl set-x11-keymap $aiKEYLANG
fi
# Autologin
if [ $aiAUTOLOGIN -eq 1 ]; then
gpasswd -a $aiUSER autologin
sed -i "s/#autologin-user=/autologin-user=${aiUSER}/" /etc/lightdm/lightdm.conf
fi
fi
# Audio
pacman -S alsa-utils pulseaudio-alsa paprefs pavucontrol --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Audio manager installation error\n"; fi
# Printer
if [ $aiPRINT = "y" ]; then
pacman -S cups cups-pdf system-config-printer --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Printing manager installation error\n"; fi
systemctl enable org.cups.cupsd
fi
# Bluetooth
if [ $aiBT = "y" ]; then
pacman -S bluez bluez-utils --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Bluetooth installation error\n"; fi
systemctl enable bluetooth
fi
# --- Software ---
pacman -S gnu-free-fonts font-bh-ttf ttf-liberation ttf-dejavu ttf-ubuntu-font-family ttf-linux-libertine ttf-opensans ttf-hannom ttf-hanazono ttf-baekmuk --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Fonts installation error\n"; fi
pacman -S gtk2-perl gtk-engine-murrine lightdm-gtk-greeter-settings gnome-packagekit git sshfs openssh wget grub-customizer rxvt-unicode xf86-input-libinput p7zip htop --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Some system software installation error\n"; fi
if [ $aiDE -gt 0 ]; then
pacman -S xarchiver hardinfo onboard catfish alacarte gnome-calculator gparted libreoffice-still vlc gimp firefox evince notepadqq geany claws-mail hexchat utox xboard gnuchess aisleriot --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Some software installation error\n"; fi
pacman -S archlinux-wallpaper adapta-gtk-theme arc-gtk-theme arc-icon-theme arc-solid-gtk-theme papirus-icon-theme breeze-gtk breeze-icons materia-gtk-theme deepin-gtk-theme deepin-icon-theme elementary-icon-theme lxde-icon-theme --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Themes installation error\n"; fi
fi
cat << 'EOT' > /etc/skel/.Xresources
*.foreground: #fafdfb
*.background: #2e3235
*.cursorColor: #fafdfb
*.color0: #282a2e
*.color8: #373b41
*.color1: #a54242
*.color9: #cc6666
*.color2: #8c9440
*.color10: #b5bd68
*.color3: #de935f
*.color11: #f0c674
*.color4: #5f819d
*.color12: #81a2be
*.color5: #85678f
*.color13: #b294bb
*.color6: #5e8d87
*.color14: #8abeb7
*.color7: #707880
*.color15: #fafdfb
URxvt*font: xft:inconsolata:size=13:antialias=true
EOT
if [ $aiLOL ]; then
pacman -S libreoffice-still-$aiLOL --noconfirm
if [ $? -gt 0 ]; then aiAE=1; aiERRORS="$aiERRORS - Libre Office language pack installation error\n"; fi
fi
pacman -Rd chromaprint --noconfirm
# - Autoupdate
case "$aiUPDATE" in
1)
printf "[Unit]\nDescription=Simple Arch auto update service\n\n[Service]\nType=idle\nRemainAfterExit=no\nExecStart=+urxvt -e bash -c 'printf \"\\\n SIMPLE ARCH AUTO UPDATE\\\n\\\n\";sudo pacman -Syu --noconfirm && paccache -rk1;bash'\n\n[Install]\nWantedBy=default.target" > /etc/systemd/user/updArch.service
printf "[Unit]\nDescription=Simple Arch auto update timer\n\n[Timer]\nOnCalendar=Mon *-*-* 11:00:00\nPersistent=true\n\n[Install]\nWantedBy=timers.target" > /etc/systemd/user/updArch.timer
systemctl --global enable updArch.timer
;;
2)
printf "[Unit]\nDescription=Simple Arch quiet auto update service\n\n[Service]\nType=idle\nRemainAfterExit=no\nExecStart=pacman -Syu --noconfirm\nExecStartPost=paccache -rk1\nStandardOutput=file:/var/log/saul.log\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/updArchS.service
printf "[Unit]\nDescription=Simple Arch quiet auto update timer\n\n[Timer]\nOnCalendar=Mon *-*-* 11:00:00\nPersistent=true\n\n[Install]\nWantedBy=timers.target" > /etc/systemd/system/updArchS.timer
systemctl enable updArchS.timer
;;
esac
# - Restart
printf "\n\n --- INSTALLATION COMPLETE ---\nRemember to review and delete installation files in /root (the file ivars contains the passwords) !\n"
if [ $aiAE -eq 1 ]; then
echo -e $aiERRORS
fi
read -p "Reboot ? (y/n): " ireply
if [ "$ireply" = "y" ]; then
reboot
fi
exit 0
